# Generated by Django 2.1.5 on 2019-02-10 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileuploader', '0002_auto_20190209_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='is_shared',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
